<?php if(isset($single_property->style)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Style</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[style]</span></li><?php endif; ?>
<?php if(isset($single_property->nounits)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Units</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nounits]</span></li><?php endif; ?>
<?php if(isset($single_property->nostories)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Stories</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nostories]</span></li><?php endif; ?>
<?php if(isset($single_property->nobuildings)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Buildings</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nobuildings]</span></li><?php endif; ?>
<?php if(isset($single_property->parkingspaces)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Parking Spaces</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[parkingspaces]</span></li><?php endif; ?>
<?php if(isset($single_property->squarefeet)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">SqFt</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[squarefeet]</span></li><?php endif; ?>
    <?php if(isset($single_property->nobaths)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Total Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nobaths]</span></li><?php endif; ?>
<?php if(isset($single_property->nofullbaths)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Full Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nofullbaths]</span></li><?php endif; ?>
<?php if(isset($single_property->no34BATHS)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">3/4 Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[no34BATHS]</span></li><?php endif; ?>
<?php if(isset($single_property->nohalfbaths)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">1/2 Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nohalfbaths]</span></li><?php endif; ?>
<?php if(isset($single_property->no14BATHS)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">1/4 Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[no14BATHS]</span></li><?php endif; ?>
    <?php if(isset($single_property->acre)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Acres</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[acre]</span></li><?php endif; ?>
<?php if(isset($single_property->proptype)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Type</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[proptype]</span></li><?php endif; ?>
<?php if(isset($single_property->propsubtype)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Sub Type</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[propsubtype]</span></li><?php endif; ?>
<?php if(isset($single_property->yearbuilt)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Built</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[yearbuilt]</span></li><?php endif; ?>
<?php if(isset($single_property->lngCOUNTYDESCRIPTION)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">County</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[lngCOUNTYDESCRIPTION]</span></li><?php endif; ?>
<?php if(isset($single_property->lngAREADESCRIPTION)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Area</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[lngAREADESCRIPTION]</span></li><?php endif; ?>
