<?php if(isset($single_property->style)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Style</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[style]</span></li><?php endif; ?>
    <?php if(isset($single_property->nobaths)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Total Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nobaths]</span></li><?php endif; ?>
<?php if(isset($single_property->nofullbaths)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Full Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nofullbaths]</span></li><?php endif; ?>
<?php if(isset($single_property->no34BATHS)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">3/4 Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[no34BATHS]</span></li><?php endif; ?>
<?php if(isset($single_property->nohalfbaths)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">1/2 Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nohalfbaths]</span></li><?php endif; ?>
<?php if(isset($single_property->no14BATHS)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">1/4 Baths</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[no14BATHS]</span></li><?php endif; ?>
    <?php if(isset($single_property->unmapped->LotSizeArea)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Acres</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[unmapped_LotSizeArea]</span></li><?php endif; ?>
<?php if(isset($single_property->nolots)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Approved Lots</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[nolots]</span></li><?php endif; ?>
<?php if(isset($single_property->neighborhood)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Neighborhood</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[neighborhood]</span></li><?php endif; ?>
<?php if(isset($single_property->proptype)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Type</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[proptype]</span></li><?php endif; ?>
<?php if(isset($single_property->propsubtype)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Sub Type</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[propsubtype]</span></li><?php endif; ?>
<?php if(isset($single_property->lngCOUNTYDESCRIPTION)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">County</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[lngCOUNTYDESCRIPTION]</span></li><?php endif; ?>
<?php if(isset($single_property->lngAREADESCRIPTION)): ?><li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Area</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">[lngAREADESCRIPTION]</span></li><?php endif; ?>
