{if field="single_property.nounits"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Units</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{nounits}}</span></li>{/if}
{if field="single_property.nostories"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Stories</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{nostories}}</span></li>{/if}
{if field="single_property.nobuildings"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Buildings</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{nobuildings}}</span></li>{/if}
{if field="single_property.parkingspaces"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Parking Spaces</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{parkingspaces}}</span></li>{/if}
{if field="single_property.squarefeet"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">SqFt</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{squarefeet}}</span></li>{/if}
{if field="single_property.acre"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Acres</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{acre}}</span></li>{/if}
{if field="single_property.customtype"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Type</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{customtype}}</span></li>{/if}
{if field="single_property.yearbuilt"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Built</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{yearbuilt}}</span></li>{/if}
{if field="single_property.lngCOUNTYDESCRIPTION"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">County</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{lngCOUNTYDESCRIPTION}}</span></li>{/if}
{if field="single_property.lngAREADESCRIPTION"}<li><label class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">Area</label> <span class="col-lg-6 col-sm-6 col-md-6 col-xs-6 col zy_nopadding">{{lngAREADESCRIPTION}}</span></li>{/if}
